name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login --username bappeda-dev-team --password ${{ secrets.GH_TOKEN }} ghcr.io
          docker build --build-arg NEXT_PUBLIC_API_URL=https://api-kertaskerja-universal.kertaskerja.cc --build-arg NEXT_PUBLIC_APP_NAME=KERTAS-KERJA . --file Dockerfile --tag ghcr.io/bappeda-dev-team/fe-kertas-kerja-universal:latest
          docker push ghcr.io/bappeda-dev-team/fe-kertas-kerja-universal:latest
          docker logout
